### PR TITLE
Couple of updates

### PR DESCRIPTION
**Pull request by xenzh**
I'm trying to use async-http-client in one of my projects. It fits my needs except for a couple of things, which I've tried to add in this change:
  * upgraded the code to use tokio-io crate instead of deprecated tokio-core::io
  * added HttpResponse::get_body()
  * HttpCodec is used internally (thanks [ndusart](https://github.com/ndusart) for his [awesome idea](https://github.com/matt2xu/async-http-client/pull/2)).
  * added http and https examples

This actually is my first pull request ever, so any feedback will be greatly appreciated.

### CODE REVIEW

**Comment by ndusart** [comment]
@xenzh, the owner (@matt2xu) of the repo does not seem responsive, I do not know any other way to ping him unfortunately...

I think this library is good as an example of how you can use futures and tokio but not as a library for real projects.

You better look at the [async module of `reqwest`](https://docs.rs/reqwest/0.8.5/reqwest/unstable/async/index.html), it is marked as *unstable* as the futures ecosystem is still not API stable so it's clearly not worse than this library and it is more likely to be actively maintained.

However, as there is not yet a big stable high-level library for making asynchronous http requests out there, this repository is still worth the look and it certainly should be updated.

For comments about your PR, I'd suggest to clean up a bit your commit history.
It's not a protected branch, you can completely rewrite your history.

So remove the commit e9b987b (replaced by 996d646).

I didn't fully review your changes, so I do not know if your work is independant of other PR (mine in this case :p), but if it is, do not depend on them. You'll enjoy both when they will get merged and it simplifies the process of reviewing them.
If it is dependant, it's preferable to base your branch upon the PR branch so you do not steal the commit or at least cherry-pick it ;)

**Comment by mwz-cg** [comment]
Hi @xenzh sorry I did not see notifications from Github :confused:  until @ndusart pinged me, so I guess using @ is a good way to reach me :smile:  I must have disabled too many notifications or something. I'll take a look at your PR and get back to you quickly!

**Comment by ndusart** [comment]
Ha, good to know that opening a PR does not push a notification at all cases ^^

**Comment by matt2xu** [comment]
Sadly enough, I also just noticed that you had opened a pull request too @ndusart. Sorry for not replying, I don't believe I have received a notification for that one either :/

So here are my remarks regarding this PR: changes look good, if that's ok with you I'll just rebase the 2 commits about `get_body` :) Would you like me to release a new version on crates.io after I merge this?

**Comment by xenzh** [comment]
@ndusart Thanks for your comment! `reqwest` async client is indeed an interesting option to consider.
I got your change out of this PR, they are pretty much independent (except the examples, they'll need to be updated after both PRs are in). Back when I did the change I was not sure that this repo is maintained and wanted to have all the patches in one place (idea of basing my change on your branch somehow didn't occur to me).

@matt2xu It's nice to see that this library is not abandoned. I cleaned my PR a bit, it should be much easier to review now. Also, backed out changes to docs and changelog - it makes more sense to do them after both PRs are merged.
Regarding crates.io release: it certainly would be nice, but there's no rush, I'm fine as long as there's an up-to-date repo to reference in `Cargo.toml`.

**Comment by matt2xu** [comment]
@xenzh great, nice work!

**Pull request merged**
